<?php

namespace Learning\FirstUnit\Block\Welcome;

use Magento\Framework\View\Element\Template;

class Introduce extends Template
{
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}

